- id: supabase
  name: Supabase
  homepageUrl: https://supabase.com/
  tags:
    - graphql
    - databases

- id: aws
  name: AWS
  homepageUrl: https://aws.amazon.com/

- id: cloudflare
  name: Cloudflare
  homepageUrl: https://www.cloudflare.com/

- id: fastly
  name: Fastly
  homepageUrl: https://www.fastly.com/

- id: github_pages
  name: GitHub Pages
  homepageUrl: https://pages.github.com/

- id: google_cloud
  name: Google Cloud
  homepageUrl: https://cloud.google.com/

- id: planetscale
  name: PlanetScale
  homepageUrl: https://planetscale.com/

- id: netlify
  name: Netlify
  homepageUrl: https://www.netlify.com/

- id: render
  name: Render
  homepageUrl: https://render.com/

- id: vercel
  name: Vercel
  homepageUrl: https://vercel.com/

- id: sentry
  name: Sentry
  homepageUrl: https://sentry.com/

- id: digital_ocean
  name: Digital Ocean
  homepageUrl: https://digitalocean.com/

- id: upstash
  name: Upstash
  homepageUrl: https://upstash.com/

- id: azure
  name: Azure
  homepageUrl: https://azure.microsoft.com/

- id: heroku
  name: Heroku
  homepageUrl: https://heroku.com/

- id: firebase
  name: Firebase
  homepageUrl: https://firebase.google.com/

- id: hetzner
  name: Hetzner
  homepageUrl: https://www.hetzner.com/

- id: vmware
  name: Hetzner
  homepageUrl: https://www.hetzner.com/

# japanese services

- id: idcf_cloud
  name: IDCF Cloud
  homepageUrl: https://www.idcf.jp/cloud/

- id: nifcloud
  name: Nifcloud
  homepageUrl: https://pfs.nifcloud.com/

- id: sakura_cloud
  name: Sakura Cloud
  homepageUrl: https://cloud.sakura.ad.jp/

- id: z_com_cloud
  name: Z.com Cloud
  homepageUrl: https://z.com/jp/
