# japanese services

- id: idcf_cloud
  name: IDCF Cloud
  homepageUrl: https://www.idcf.jp/cloud/

- id: nifcloud
  name: Nifcloud
  homepageUrl: https://pfs.nifcloud.com/

- id: sakura_cloud
  name: Sakura Cloud
  homepageUrl: https://cloud.sakura.ad.jp/

- id: z_com_cloud
  name: Z.com Cloud
  homepageUrl: https://z.com/jp/

# other services

- id: supabase
  name: Supabase
  homepageUrl: https://supabase.com/
  tags:
    - graphql
    - databases

- id: aws
  name: AWS
  homepageUrl: https://aws.amazon.com/

- id: cloudflare
  name: Cloudflare
  homepageUrl: https://www.cloudflare.com/

- id: fastly
  name: Fastly
  homepageUrl: https://www.fastly.com/

- id: github_pages
  name: GitHub Pages
  homepageUrl: https://pages.github.com/

- id: google_cloud
  name: Google Cloud
  homepageUrl: https://cloud.google.com/
  patterns:
    - gcp

- id: planetscale
  name: PlanetScale
  homepageUrl: https://planetscale.com/

- id: netlify
  name: Netlify
  homepageUrl: https://www.netlify.com/

- id: render
  name: Render
  homepageUrl: https://render.com/
  tags:
    - edge_runtimes

- id: vercel
  name: Vercel
  homepageUrl: https://vercel.com/

- id: sentry
  name: Sentry
  homepageUrl: https://sentry.com/

- id: digital_ocean
  name: Digital Ocean
  homepageUrl: https://digitalocean.com/

- id: upstash
  name: Upstash
  homepageUrl: https://upstash.com/

- id: azure
  name: Azure
  homepageUrl: https://azure.microsoft.com/

- id: heroku
  name: Heroku
  homepageUrl: https://heroku.com/

- id: firebase
  name: Firebase
  homepageUrl: https://firebase.google.com/

- id: hetzner
  name: Hetzner
  homepageUrl: https://www.hetzner.com/

- id: vmware
  name: Hetzner
  homepageUrl: https://www.hetzner.com/

- id: netlify
  name: Netlify
  homepageUrl: https://www.netlify.com/

- id: linode
  name: Linode
  homepageUrl: https://www.linode.com/

- id: alibaba_cloud
  name: Alibaba Cloud
  patterns:
    - alibaba [p]
    - ali [p]
  homepageUrl: https://www.alibabacloud.com/

- id: clever_cloud
  name: Clever Cloud
  patterns:
    - clever [p]
  homepageUrl: https://www.clever-cloud.com/

- id: coolify
  name: Coolify
  homepageUrl: https://coolify.io/

- id: cyclic
  name: Cyclic
  homepageUrl: https://www.cyclic.sh/
  patterns:
    - cyclic [p]

- id: deno_deploy
  name: Deno Deploy
  homepageUrl: https://deno.com/deploy
  patterns:
    - deno [p]

- id: dreamhost
  name: Dreamhost
  homepageUrl: https://www.dreamhost.com/

- id: gitlab
  name: GitLab Pages
  patterns:
    - gitlab
  homepageUrl: https://docs.gitlab.com/ee/user/project/pages/

- id: hostinger
  name: Hostinger
  homepageUrl: https://www.hostinger.com/

- id: ionos
  name: IONOS
  homepageUrl: https://www.ionos.com/

- id: koyeb
  name: Koyeb
  homepageUrl: https://www.koyeb.com/

- id: kubernetes
  name: Kubernetes
  homepageUrl: https://kubernetes.io/
  patterns:
    - k8s

- id: meteor_cloud
  name: Meteor Cloud
  patterns:
    - meteor
  homepageUrl: https://cloud.meteor.com/

- id: netcup
  name: netcup
  homepageUrl: https://www.netcup.eu/

- id: northflank
  name: Northflank
  homepageUrl: https://northflank.com/

- id: openshift
  name: OpenShift
  homepageUrl: https://www.redhat.com/en/technologies/cloud-computing/openshift/try-it

- id: oracle_cloud
  name: Oracle Cloud
  homepageUrl: https://www.oracle.com/cloud/
  patterns:
    - oracle
    - oci

- id: ovh
  name: OVH
  homepageUrl: https://www.ovhcloud.com/
  patterns:
    - ovhcloud

- id: railway
  name: Railway
  homepageUrl: https://railway.app/

- id: scaleway
  name: Scaleway
  homepageUrl: https://www.scaleway.com/

- id: self_hosted
  name: Self-hosted
  patterns:
    - on prem
    - on premise
    - self( |-)?hosted
    - own server
    - own machine
    - custom server
    - own hosting
    - self(-| )?host
    - self(-| )?hosting

- id: surge
  name: Surge
  patterns:
    - surge [p]
  homepageUrl: https://surge.sh/

- id: vps
  name: VPS

- id: vultr
  name: Vultr
  homepageUrl: https://www.vultr.com/

- id: yandex_cloud
  name: Yandex Cloud
  patterns:
    - yandex
  hompageUrl: https://cloud.yandex.com/

- id: aws_amplify
  name: AWS Amplify
  homepageUrl: https://aws.amazon.com/amplify/
  patterns:
    - amplify

- id: contabo
  name: Contabo
  homepageUrl: https://contabo.com/

- id: glitch
  name: Glitch
  homepageUrl: https://glitch.com/

- id: infomaniak
  name: Infomaniak
  homepageUrl: https://www.infomaniak.com/

- id: ibm_cloud
  name: IBM Cloud
  homepageUrl: https://www.ibm.com/cloud

- id: dokploy
  name: Dokploy
  homepageUrl: https://dokploy.com/

- id: caprover
  name: CapRover
  homepageUrl: https://caprover.com/

- id: codeberg_pages
  name: Codeberg Pages
  homepageUrl: https://docs.codeberg.org/codeberg-pages/

- id: dokku
  name: Dokku
  homepageUrl: https://dokku.com/

###
# Auth
###

- id: aws_cognito
  name: AWS Cognito
  homepageUrl: https://aws.amazon.com/cognito/
  patterns:
    - cognito

- id: descope
  name: Descope
  homepageUrl: https://www.descope.com/

- id: frontegg
  name: Frontegg
  homepageUrl: https://frontegg.com/

- id: gigya
  name: Gigya (SAP)
  homepageUrl: https://www.sap.com

- id: keycloak
  name: Keycloak
  homepageUrl: https://www.keycloak.org/

- id: okta
  name: Okta
  homepageUrl: https://www.okta.com/

- id: slashid
  name: /id
  homepageUrl: https://www.slashid.dev/
  patterns:
    - slashid

- id: stytch
  name: Stytch
  homepageUrl: https://stytch.com/

- id: supertokens
  name: SuperTokens
  github: supertokens/supertokens-core
  homepageUrl: https://supertokens.com/

- id: userfront
  name: Userfront
  homepageUrl: https://userfront.com/

- id: amplitude

- id: appwrite

- id: axiom

- id: bugsnag

- id: clerk

- id: cockroach_db

- id: contentful

- id: convex

- id: launch_darkly

- id: log_rocket

- id: mongodb_atlas

- id: neon
  name: Neon
  homepageUrl: https://neon.tech/

- id: pocket_base

- id: resend

- id: rollbar

- id: sanity

- id: turso
  name: Turso
  homepageUrl: https://turso.tech/

- id: typeorm

- id: uploadthing

- id: gatsby_cloud

- id: xata
  name: Xata
  homepageUrl: https://xata.io/

- id: clickup

- id: gather

- id: webex

- id: zulip

- id: mattermost

- id: miro

- id: pagespeed_insights
  name: PageSpeed Insights
  homepageUrl: https://pagespeed.web.dev/
  patterns:
    - pagespeed
  tags:
    - performance

- id: webpagetest
  name: WebPageTest
  homepageUrl: https://www.webpagetest.org/
  tags:
    - performance

- id: pingdom
  name: Pingdom
  homepageUrl: https://www.pingdom.com/
  tags:
    - performance

- id: google_analytics
  name: Google Analytics
  homepageUrl: https://analytics.google.com/
  tags:
    - analytics

- id: plausible
  name: Plausible Analytics
  homepageUrl: https://plausible.io/
  tags:
    - analytics

- id: fathom
  name: Fathom Analytics
  homepageUrl: https://usefathom.com/
  tags:
    - analytics

- id: new_relic
  name: New Relic
  homepageUrl: https://newrelic.com/
  tags:
    - analytics

- id: mixpanel
  name: Mixpanel
  homepageUrl: https://mixpanel.com/
  tags:
    - analytics

- id: clicky
  name: Clicky
  homepageUrl: https://clicky.com/
  tags:
    - analytics

- id: matomo
  name: Matomo
  homepageUrl: https://matomo.org/
  tags:
    - analytics

- id: heap
  name: Heap
  homepageUrl: https://www.heap.io/
  tags:
    - analytics

- id: datadog
  name: Datadog
  homepageUrl: https://www.datadoghq.com/
  tags:
    - analytics

- id: gt_metrix
  name: GTmetrix
  homepageUrl: https://gtmetrix.com/

- id: speed_curve
  name: SpeedCurve
  homepageUrl: https://www.speedcurve.com/

- id: up_time_robot
  name: UptimeRobot
  homepageUrl: https://uptimerobot.com/

- id: yellow_lab_tools
  name: Yellow Lab tools
  homepageUrl: https://yellowlab.tools/
  patterns:
    - yellow, lab [l]

- id: adobe_analytics
  name: Adobe Analytics
  homepageUrl: https://business.adobe.com/products/analytics/adobe-analytics.html

- id: azure_application_insights
  name: Azure Application Insights
  homepageUrl: https://learn.microsoft.com/en-us/azure/azure-monitor/app/app-insights-overview
  patterns:
    - application, insights [l]

- id: app_signal
  name: AppSignal
  homepageUrl: https://www.appsignal.com/

- id: microsoft_clarity
  name: Clarity
  homepageUrl: https://clarity.microsoft.com/
  patterns:
    - clarity

- id: full_story
  name: Fullstory
  homepageUrl: https://www.fullstory.com/

- id: go_access
  name: GoAccess
  homepageUrl: https://goaccess.io/

- id: goat_counter
  name: GoatCounter
  homepageUrl: https://www.goatcounter.com/

- id: grafana
  name: Grafana
  homepageUrl: https://grafana.com/

- id: hot_jar
  name: Hotjar
  homepageUrl: https://www.hotjar.com/

- id: post_hog
  name: PostHog
  homepageUrl: https://posthog.com/

- id: umami
  name: Umami
  homepageUrl: https://umami.is/

- id: mailchimp
  name: Mailchimp
  homepageUrl: https://mailchimp.com/
  patterns:
    - mailchi.mp

- id: outlook
  name: Microsoft Outlook
  homepageUrl: https://www.microsoft.com/en-us/microsoft-365/outlook/email-and-calendar-software-microsoft-outlook
  patterns:
    - outlook.live.com
